from .utils import ImmutableMatrix, Coordinate, Direction

class SokobanMap:

    __slots__ = ("_matrix", "_position", "_hash")

    def __init__(self, matrix: ImmutableMatrix, position: Coordinate) -> None:
        if not (isinstance(tiles, list) or isinstance(tiles, tuple)):
            raise TypeError("Argument must be a list or tuple")

        expected = set(range(_SIZE ** 2))
        if len(tiles) != _SIZE ** 2 or set(tiles) != expected:
            raise ValueError(f"Argument must be a permutation of {sorted(expected)}, got {tiles!r}")

        self._tiles: tuple[int, ...] = tuple(tiles)
        self._blank_index: int = tiles.index(0)
        self._hash: int = hash(self._tiles)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, EightPuzzleBoard):
            return False
        return self._tiles == other._tiles

    def __hash__(self) -> int:
        return self._hash

    def __getitem__(self, position: tuple[int, int]) -> int:
        row, col = position
        if not (0 <= row < _SIZE and 0 <= col < _SIZE):
            raise IndexError(f"position {position} out of range for a {_SIZE}×{_SIZE} board")
        return self._tiles[row * _SIZE + col]

    def __repr__(self) -> str:
        return f"{type(self).__name__}({self._tiles!r})"

    def __str__(self) -> str:
        s = ""
        for i in range(_SIZE):
            row = self._tiles[i * _SIZE: (i + 1) * _SIZE]
            s += " ".join([str(x) for x in row]) + "\n"
        return s

    @property
    def tiles(self) -> tuple[int, ...]:
        """Get the tiles represented by this :class:`EightPuzzleBoard`."""
        return self._tiles

    @property
    def blank_position(self) -> tuple[int, int]:
        """Get the position of the blank tiles represented by this :class:`EightPuzzleBoard`."""
        return divmod(self._blank_index, _SIZE)

    def move(self, direction: Direction) -> EightPuzzleBoard | None:
        """Slide a tile into the blank space from *direction*.

        This effectively moves the blank one step in the given :class:`Direction`.
        Returns a new board with the move applied, or ``None`` if the move is illegal (would go out of bounds).

        :param direction: :class:`Direction`: The direction to move the blank.
        """
        blank_row, blank_col = self.blank_position
        d_row, d_col = direction.value
        new_row, new_col = blank_row + d_row, blank_col + d_col

        if not (0 <= new_row < _SIZE and 0 <= new_col < _SIZE):
            return None

        new_index = new_row * _SIZE + new_col
        tiles = list(self._tiles)
        tiles[self._blank_index], tiles[new_index] = tiles[new_index], tiles[self._blank_index]
        return EightPuzzleBoard(tiles)

    def neighbours(self) -> Iterator[tuple[Direction, EightPuzzleBoard]]:
        """Yield all reachable neighbour states with the move that produced them. Each time, returns a pair that
        contains a Direction and the board generated by moving in that direction.
        """
        for direction in Direction:
            neighbour = self.move(direction)
            if neighbour is not None:
                yield direction, neighbour
